### ISSUE TITLE
use firecharges to set entities on fire like flint & steel

### ISSUE THREAD

**Issue by yesn0t** [DeflatedPickle/CombustibleEntities#1]
I hope it's not outside the scope of this mod, would really love to see firecharges become useful in minecraft x)
the firecharge sound would be a plus

**Comment by DeflatedPickle** [comment]
It definitely is! Like most things in vanilla, I completely forgot they existed! I'll add support for them when I next work on the mod. Thank you for suggesting it!

**Comment by yesn0t** [comment]
awesome, looking forwards to it :D
